# Generated by Django 6.0.2 on 2026-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome icon (e.g., fa-share-nodes)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='পয়েন্টগুলো কমা (,) দিয়ে লিখুন। যেমন: Facebook Ads, Content Plan')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
