# Generated by Django 6.0.2 on 2026-03-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_remove_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='business_website',
        ),
        migrations.AddField(
            model_name='consultation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='বিস্তারিত'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
