# Generated by Django 6.0.2 on 2026-03-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_consultation_business_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
