# Generated by Django 6.0.2 on 2026-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_consultation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Professional Experience Certificates', max_length=255)),
                ('akr_cert', models.ImageField(upload_to='certificates/', verbose_name='AKR Technology')),
                ('infinity_cert', models.ImageField(upload_to='certificates/', verbose_name='Infinity Technology')),
                ('elearning_cert', models.ImageField(upload_to='certificates/', verbose_name='e-Learning & Earning')),
            ],
        ),
    ]
